class_names = [
    "abyssinian ground hornbill",
    "african crowned crane",
    "alexandrine parakeet",
    "altamira yellowthroat",
    "anianiau",
    "araripe manakin",
    "ashy storm petrel",
    "ashy thrushbird",
    "asian crested ibis",
    "auckland shaq",
    "azure breasted pitta",
    "azure jay",
    "azure tanager",
    "bald ibis",
    "bali starling",
    "banded broadbill",
    "bar-tailed godwit",
    "black and yellow broadbill",
    "black cockato",
    "black faced spoonbill",
    "bornean bristlehead",
    "bornean pheasant",
    "bulwers pheasant",
    "cabots tragopan",
    "california condor",
    "cerulean warbler",
    "chattering lory",
    "common grackle",
    "crested fireback",
    "crested wood partridge",
    "dalmatian pelican",
    "dusky robin",
    "eastern meadowlark",
    "eastern wip poor will",
    "elliots  pheasant",
    "emperor penguin",
    "european turtle dove",
    "evening grosbeak",
    "fairy tern",
    "fiery minivet",
    "fiordland penguin",
    "gang gang cockatoo",
    "gold wing warbler",
    "golden bower bird",
    "golden cheeked warbler",
    "golden parakeet",
    "great tinamou",
    "greater prairie chicken",
    "greator sage grouse",
    "green broadbill",
    "grey headed fish eagle",
    "gurneys pitta",
    "harpy eagle",
    "hawaiian goose",
    "helmet vanga",
    "horned guan",
    "hyacinth macaw",
    "inca tern",
    "indian bustard",
    "indian vulture",
    "ivory gull",
    "java sparrow",
    "jocotoco antpitta",
    "kagu",
    "kakapo",
    "kiwi",
    "lesser adjutant",
    "loggerhead shrike",
    "malabar hornbill",
    "maleo",
    "masked bobwhite",
    "mikado  pheasant",
    "military macaw",
    "nicobar pigeon",
    "ocellated turkey",
    "ornate hawk eagle",
    "palila",
    "philippine eagle",
    "quetzal",
    "red knot",
    "red naped trogon",
    "snowy owl",
    "sri lanka blue magpie",
    "striated caracara",
    "swinhoes pheasant",
    "takahe",
    "tricolored blackbird",
    "victoria crowned pigeon",
    "visayan hornbill",
    "wattled curassow",
    "wilsons bird of paradise",
]
