class_names = [
    "african crowned crane",
    "anianiau",
    "araripe manakin",
    "ashy storm petrel",
    "asian crested ibis",
    "bald ibis",
    "bali myna",
    "black cockato",
    "black faced spoonbill",
    "bornean peacock-pheasant",
    "california condor",
    "golden cheeked warbler",
    "gurneys pitta",
    "helmet vanga",
    "horned guan",
    "indian bustard",
    "indian vulture",
    "java sparrow",
    "jocotoco antpitta",
    "kagu",
    "kakapo",
    "maleo",
    "palila",
    "philippine eagle",
    "takahe",
    "tricolored blackbird",
    "visayan hornbill",
    "wattled curassow",
]
